import { Injectable } from '@angular/core';
import { Project } from './project';

@Injectable({
  providedIn: 'root',
})
export class WEBProjectsService {
  constructor() {}

  WebProjects: Project[] = [
    {
      id: 1,
      category: 'Web-Apps',
      name: 'RK Maps',
      desc: 'RK Maps is a powerful web and mobile application for uploading urban data, creating interactive maps online, and offering advanced features like AI-driven building detection and real-time chat.',
      mainImg: './assets/detail_Projects/web/RK.MAPS/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/RK.MAPS/sub/1.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/2.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/3.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/4.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/5.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/6.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/7.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/8.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/9.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/10.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/11.webp',
        './assets/detail_Projects/web/RK.MAPS/sub/12.webp',
      ],
      tech: ['Angular', 'Tailwind CSS', 'Node.js', 'Express.js', 'MongoDB'],
      video: 'https://www.facebook.com/100001750802724/videos/445272268384902/',
      fronendGit: 'https://github.com/rafat962/R.K-Maps-frontend.git',
      backendGit: 'https://github.com/rafat962/RK.maps-backend.git',
    },
    {
      id: 14,
      category: 'Web-Apps',
      name: 'Geo-Platform',
      desc: 'A web app for managing and visualizing geospatial data, built with React, Framer Motion, Node.js, Express, and MongoDB. It features a smooth, animated interface for an immersive user experience.',
      mainImg: './assets/detail_Projects/web/Geo-Platform/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/Geo-Platform/sub/1.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/2.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/2.2.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/2.3.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/3.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/4.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/5.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/6.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/7.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/8.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/9.webp',
        './assets/detail_Projects/web/Geo-Platform/sub/10.webp',
      ],
      tech: [
        'Reactjs',
        'ReactQuery',
        'Tailwind CSS',
        'Node.js',
        'Express.js',
        'MongoDB',
      ],
      fronendGit: 'https://github.com/rafat962/Geo_Platform.git',
    },
    {
      id: 3,
      category: 'Web-Apps',
      name: 'A 3D interactive portfolio',
      desc: 'A 3D interactive portfolio built with React and Framer Motion, showcasing projects and skills through smooth animations and an immersive user experience.',
      mainImg: './assets/detail_Projects/web/3dPortfolio/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/3dPortfolio/main/main.webp',
        './assets/detail_Projects/web/3dPortfolio/sub/2.webp',
        './assets/detail_Projects/web/3dPortfolio/sub/3.webp',
        './assets/detail_Projects/web/3dPortfolio/sub/3.3.webp',
        './assets/detail_Projects/web/3dPortfolio/sub/4.webp',
        './assets/detail_Projects/web/3dPortfolio/sub/5.webp',
        './assets/detail_Projects/web/3dPortfolio/sub/6.webp',
      ],
      tech: ['Reactjs', 'ReactQuery'],
      fronendGit: 'https://github.com/rafat962/3dPortfolio.git',
    },
    {
      id: 2,
      category: 'Web-Apps',
      name: 'Sallat Al-Mona',
      desc: 'Sallat Al-Mona is a dedicated online platform for selling Kuwaiti food products, offering a seamless shopping experience with authentic local flavors.',
      mainImg: './assets/detail_Projects/web/Sallat Al-Mona/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/Sallat Al-Mona/sub/1.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/2.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/3.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/4.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/5.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/6.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/7.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/8.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/9.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/10.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/11.webp',
        './assets/detail_Projects/web/Sallat Al-Mona/sub/12.webp',
      ],
      tech: ['Angular', 'Tailwind CSS', 'Node.js', 'Express.js', 'MongoDB'],
      video: 'https://www.facebook.com/100001750802724/videos/711011464437756',
      fronendGit: 'https://github.com/rafat962/SALLAT_AL_MONA_FRONTEND.git',
      backendGit: 'https://github.com/rafat962/salet_mona_backend.git',
    },
    {
      id: 9,
      category: 'Web-Apps',
      name: 'THE_WILD_OASIS',
      desc: 'A web-based cabin booking and management system for a hotel, where staff can track available cabins and manage reservations through an interactive map and custom-built widgets.',
      mainImg: './assets/detail_Projects/web/THE_WILD_OASIS/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/1.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/2.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/3.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/4.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/5.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/6.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/7.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/8.webp',
        './assets/detail_Projects/web/THE_WILD_OASIS/sub/9.webp',
      ],
      tech: ['Reactjs', 'ReactQuery', 'SupBase'],
      fronendGit: 'https://github.com/rafat962/the-waild-oasis.git',
    },

    {
      id: 4,
      category: 'Web-Apps',
      name: 'Real Estate',
      desc: 'Real Estate is a web platform for managing properties, showcasing listings with map integrations and advanced search features.',
      mainImg: './assets/detail_Projects/web/RealState/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/RealState/sub/1.webp',
        './assets/detail_Projects/web/RealState/sub/2.webp',
        './assets/detail_Projects/web/RealState/sub/3.webp',
        './assets/detail_Projects/web/RealState/sub/4.webp',
        './assets/detail_Projects/web/RealState/sub/5.webp',
        './assets/detail_Projects/web/RealState/sub/6.webp',
        './assets/detail_Projects/web/RealState/sub/7.webp',
        './assets/detail_Projects/web/RealState/sub/8.webp',
      ],
      tech: [
        'Angular',
        'Tailwind CSS',
        'Node.js',
        'Express.js',
        'MongoDB',
        'Mapbox',
      ],
      fronendGit: 'https://github.com/rafat962/realstateFrontend.git',
      backendGit: 'https://github.com/rafat962/realstateBackend.git',
    },
    {
      id: 6,
      category: 'Web-Apps',
      name: 'Natours',
      desc: 'Natours is a backend-powered travel booking platform built with Node.js, MongoDB, Express.js, and Pug.js, featuring secure payment options and seamless user experience.',
      mainImg: './assets/detail_Projects/web/Natours/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/Natours/sub/1.webp',
        './assets/detail_Projects/web/Natours/sub/2.webp',
        './assets/detail_Projects/web/Natours/sub/3.webp',
        './assets/detail_Projects/web/Natours/sub/4.webp',
        './assets/detail_Projects/web/Natours/sub/5.webp',
        './assets/detail_Projects/web/Natours/sub/6.webp',
        './assets/detail_Projects/web/Natours/sub/7.webp',
        './assets/detail_Projects/web/Natours/sub/8.webp',
        './assets/detail_Projects/web/Natours/sub/9.webp',
        './assets/detail_Projects/web/Natours/sub/10.webp',
        './assets/detail_Projects/web/Natours/sub/11.webp',
      ],
      tech: ['Node.js', 'Express.js', 'MongoDB', 'Pug.js'],
      video:
        'https://www.facebook.com/100001750802724/videos/7408196959200327/',
      backendGit: 'https://github.com/rafat962/natours.git',
    },
    {
      id: 5,
      category: 'Web-Apps',
      name: 'Rentize',
      desc: 'Rentize is a real estate platform showcasing apartments for sale and rent, with features to display listings on a map and view nearby requests.',
      mainImg: './assets/detail_Projects/web/RENTIZE/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/RENTIZE/sub/1.webp',
        './assets/detail_Projects/web/RENTIZE/sub/2.webp',
        './assets/detail_Projects/web/RENTIZE/sub/3.webp',
        './assets/detail_Projects/web/RENTIZE/sub/4.webp',
        './assets/detail_Projects/web/RENTIZE/sub/5.webp',
        './assets/detail_Projects/web/RENTIZE/sub/6.webp',
      ],
      tech: [
        'ArcGIS Pro',
        'ArcGIS Online',
        'Python',
        'HTML',
        'CSS',
        'JavaScript',
        'Django',
      ],
      video: 'https://www.facebook.com/100001750802724/videos/808769784129457/',
    },
    {
      id: 7,
      category: 'Web-Apps',
      name: 'Market API',
      desc: 'Market API is a web platform utilizing ESRI APIs to locate branches, find the nearest routes, define service areas, and provide interactive dashboards.',
      mainImg: './assets/detail_Projects/web/Market_api/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/Market_api/sub/1.webp',
        './assets/detail_Projects/web/Market_api/sub/2.webp',
        './assets/detail_Projects/web/Market_api/sub/3.webp',
        './assets/detail_Projects/web/Market_api/sub/4.webp',
        './assets/detail_Projects/web/Market_api/sub/5.webp',
      ],
      tech: ['Angular', 'ESRI APIs'],
      video:
        'https://www.facebook.com/100001750802724/videos/1439386669972950/',
      fronendGit: 'https://github.com/rafat962/ArcGis-apis.git',
    },
    {
      id: 8,
      category: 'Web-Apps',
      name: 'Web AI Car Detector',
      desc: 'This web project features a model for counting vehicles and calculating their speeds, all accessible online. Unlike desktop versions limited to users with the code and technical knowledge, this web-based solution allows anyone to upload and analyze their data easily.',
      mainImg:
        './assets/detail_Projects/web/Web_ai_car_Detector/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/Web_ai_car_Detector/sub/2.webp',
        './assets/detail_Projects/web/Web_ai_car_Detector/sub/3.webp',
        './assets/detail_Projects/web/Web_ai_car_Detector/sub/4.webp',
        './assets/detail_Projects/web/Web_ai_car_Detector/sub/5.webp',
        './assets/detail_Projects/web/Web_ai_car_Detector/sub/6.webp',
      ],
      tech: ['HTML', 'CSS', 'JavaScript', 'Django'],
      video: 'https://www.facebook.com/100001750802724/videos/836407348022030/',
    },
    {
      id: 10,
      category: 'Web-Apps',
      name: 'CMV',
      desc: 'A React-based web GIS application using ArcGIS API and ArcGIS Online, featuring custom widgets to display and share specific map layers with clients.',
      mainImg: './assets/detail_Projects/web/CMV/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/CMV/sub/1.webp',
        './assets/detail_Projects/web/CMV/sub/2.webp',
        './assets/detail_Projects/web/CMV/sub/3.webp',
      ],
      tech: ['Reactjs', 'ReactQuery'],
      video:
        'https://www.facebook.com/100001750802724/videos/7408196959200327/',
      backendGit: 'https://github.com/rafat962/natours.git',
    },
    {
      id: 11,
      category: 'Web-Apps',
      name: 'Moon Clothes',
      desc: 'Moon is an online platform specializing in selling stylish and high-quality clothing, offering a seamless shopping experience for all.',
      mainImg: './assets/detail_Projects/web/MOON_Clothes/main/main.webp',
      subImgs: [
        './assets/detail_Projects/web/MOON_Clothes/sub/1.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/2.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/3.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/4.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/5.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/6.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/7.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/8.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/9.webp',
        './assets/detail_Projects/web/MOON_Clothes/sub/10.webp',
      ],
      tech: ['Angular', 'HTML', 'CSS', 'Firebase'],
      video:
        'https://www.facebook.com/100001750802724/videos/1286703635343544/',
      fronendGit: 'https://github.com/rafat962/clothes-Market.git',
    },
  ];

  getOne(id: any) {
    return this.WebProjects.filter((item: Project) => item.id === id)[0];
  }
}
